# This is a basic workflow to help you get started with Actions

name: generate-wiki-site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - name: Generate Wiki
      # This command internally calls `hexo clean` and `hexo generate --wiki`.
      # Since `hexo` is not globally installed on runners of GitHub Actions, we call it in this way.
      # You need to set npm scripts to clean and build-wiki commands.
      run: |
        npm run clean &&
        npm run build-wiki
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install igem-wikisync
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Deploy to iGEM
      env:
        # You need to set secrets
        IGEM_USERNAME: ${{ secrets.IGEM_USERNAME }}
        IGEM_PASSWORD: ${{ secrets.IGEM_PASSWORD }}
      run: python wikisync.py
    - name: Commit Wiki
      # Since upload_map.yml might be updated, you have to commit and push the change.
      # For more information, please visit our Software page (https://2021.igem.org/Team:UTokyo/Software).
      run: |
        git status &&
        git add . &&
        git config --global user.email "hexogem-automated@example.com",
        git config --global user.name "hexogem-automated"
        git commit --allow-empty -m "[CI] updated upload map" &&
        git push origin master
    - run: mkdir -p /home/runner/.npm